### PR TITLE
Update demo.py

### PR DESCRIPTION
**Pull request by lfierce2**
I added the path to the model executables (i.e., where they were installed via ambuilder).

### CODE REVIEW

**Review by jeff-cohere — COMMENTED** [review]
The reason I didn't do this is that it won't work "out of the box". If we give instructions in the AMBuilder docs to make sure to install the models somewhere in a user's PATH (which is one of the first things one should learn to do in UNIX), the `demo.py` script can just be run as-is.

This is just my reasoning, but in my experience people expect something called `demo.py` to work without editing it. Open to whatever, though.

**Comment by lfierce2** [comment]
Ah. I see. That makes reasoning makes sense, but we need to add the
instructions to AMBuilder so that AMBRS actually runs the models. :)

**Comment by jeff-cohere** [comment]
Fair enough! I'll add those instructions.

**Comment by jeff-cohere** [comment]
Should we close this pull request? Also, do you want to talk about merging any of the branches we have going? If we want to merge the ones I've worked, on, we could do  `postprocessing`, `species`, and then `mphys-1-moment-sectional`. But maybe you have changes that you'd like to merge into `postprocessing` first, for example?

**Pull request closed without merging**
